### ISSUE TITLE
broken link?

### ISSUE THREAD

**Issue by andrewliao11** [ronghanghu/natural-language-object-retrieval#2]
![66](https://cloud.githubusercontent.com/assets/10975252/16439994/47812d62-3df0-11e6-92c1-651088d144e2.png)

**Comment by ronghanghu** [comment]
Not sure why this is happening. Could you try the link in your browser and see if it works? http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referit_edgeboxes_top100.zip

**Comment by andrewliao11** [comment]
ohh it suddenly work, somehow.
anyway, thx!
