### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by Pranomvignesh** [ronghanghu/natural-language-object-retrieval#6]
Hi @ronghanghu ,

When I tried to run the `./external/download_caffe.sh` file, I'm not able to download the zip file.
When I tried to load this [http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/caffe-natural-language-object-retrieval.zip](http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/caffe-natural-language-object-retrieval.zip) in web browser, it said Resource not found.

I request you to provide me the proper link to download the zip file

**Comment by wxk2024** [comment]
i encounter the same problem! have you solved?
